Small Update
Treeofsavior/EnglishTranslation pull request #1676
Opened 2016-10-12 09:49 UTC by sunhwapark

Just a few basic changes for now.
I'll look through more of the story-line later this week.

2016-10-12 12:23 UTC, sunhwapark commented
There's 2 minor commits i've made to fix the symbols on to be added soon.
QUEST_LV_0300_20160811_003234
(the other line i can't recall)

2016-10-12 12:24 UTC, Sunaries requested changes

2016-10-12 12:24 UTC, Sunaries commented on EnglishTranslation-master/QUEST_LV_0300.tsv
>  QUEST_LV_0300_20160811_003233	I did say something about ?쐅iving something in return?? right?{nl}
`?쐅iving` gibberish?

2016-10-12 12:26 UTC, sunhwapark commented on EnglishTranslation-master/QUEST_LV_0300.tsv
>  QUEST_LV_0300_20160811_003233	I did say something about ?쐅iving something in return?? right?{nl}
Yeah it's gibberish, it should say 'giving' , i have made a commit to fix it but i'm not able to push commits at the moment until i get home in a few hours. ( i lost net access when attempting to sync the aforementioned corrections )

2016-10-13 00:53 UTC, Sunaries commented
Good to merge. 👍

2016-10-17 05:09 UTC, merged